# pubspec.yaml - archivo de configuracion del proyecto flutter
# define el nombre, version, dependencias y assets del proyecto
name: villafood_frontend
description: "aplicacion movil y web para gestion de servicios alimenticios del centro educativo"
# version de la aplicacion
version: 1.0.0+1
# configuracion del entorno flutter
environment:
  sdk: '>=3.1.0 <4.0.0'
# dependencias - librerias que usa el proyecto
dependencies:
  # flutter sdk - framework base de flutter (obligatorio)
  flutter:
    sdk: flutter
    
  # --- dependencias de idiomas ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # ------------------------------------------

  # --- dependencias de graficas 
  fl_chart: ^0.68.0
  

  # http - libreria para hacer peticiones http al backend
  http: ^1.1.0
  provider: ^6.1.5+1
  # shared_preferences - persiste preferencias del usuario entre sesiones
  shared_preferences: ^2.2.2
  # dependencias de la tarea 15 imagenes y supabase
  supabase_flutter: ^2.3.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
# dependencias de desarrollo - solo para desarrollo, no van en la app final
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# configuracion de flutter
flutter:
  uses-material-design: true
  
  # --- activa la generacion automatica de traducciones ---
  generate: true
  
  assets:
    - assets/Logo_VF.png